### ISSUE TITLE
Contact Us : Contact Us tab is missing

### ISSUE THREAD

**Issue by ketulpatel03-zz** [ankit-github/cricket-tournament#7]
Under Contact Us tab : 

1. Cell No.
2. Mail Id 

For ex. 

![screenshot_1](https://user-images.githubusercontent.com/24803494/33875049-ef97dfac-df46-11e7-8188-9f24dec7ad6d.jpg)

Purpose of such requirement : helpful in any confusion regarding rules or to find the way to destination ground

**Comment by ankit-github** [comment]
Added contact details in footer
